#ifndef STS_LIGHTSPEED_JAVACARDLIBRARYORDER_H
#define STS_LIGHTSPEED_JAVACARDLIBRARYORDER_H

#include <array>

#include "constants/Cards.h"

namespace sts {
namespace JavaCardLibraryOrder {
static constexpr std::array<CardId, 370> cards = {
    CardId::IMMOLATE, CardId::GRAND_FINALE, CardId::REGRET, CardId::CRIPPLING_CLOUD, CardId::STORM, CardId::DEUS_EX_MACHINA, CardId::A_THOUSAND_CUTS, CardId::SPOT_WEAKNESS, CardId::GENETIC_ALGORITHM, CardId::GO_FOR_THE_EYES, CardId::ZAP, CardId::OVERCLOCK,
    CardId::WOUND, CardId::CORE_SURGE, CardId::FISSION, CardId::WRITHE, CardId::BETA, CardId::HELLO_WORLD, CardId::CREATIVE_AI, CardId::DARK_SHACKLES, CardId::GLASS_KNIFE, CardId::CONSECRATE, CardId::CLOAK_AND_DAGGER, CardId::BOWLING_BASH,
    CardId::SNEAKY_STRIKE, CardId::ANGER, CardId::STORM_OF_STEEL, CardId::WHEEL_KICK, CardId::CLEAVE, CardId::BALL_LIGHTNING, CardId::WARCRY, CardId::SUNDER, CardId::GLACIER, CardId::INFLAME, CardId::SADISTIC_NATURE, CardId::JAX,
    CardId::OFFERING, CardId::SIMMERING_FURY, CardId::FLYING_SLEEVES, CardId::EXHUME, CardId::STREAMLINE, CardId::FORESIGHT, CardId::CONSUME, CardId::POWER_THROUGH, CardId::DUAL_WIELD, CardId::DEADLY_POISON, CardId::LEG_SWEEP, CardId::PANIC_BUTTON,
    CardId::FLEX, CardId::RECURSION, CardId::ASCENDERS_BANE, CardId::DAGGER_SPRAY, CardId::BULLET_TIME, CardId::FUSION, CardId::CATALYST, CardId::SANCTITY, CardId::HALT, CardId::REAPER, CardId::SHIV, CardId::BANE,
    CardId::TACTICIAN, CardId::JUST_LUCKY, CardId::INFERNAL_BLADE, CardId::AFTER_IMAGE, CardId::UNLOAD, CardId::FLURRY_OF_BLOWS, CardId::BLADE_DANCE, CardId::DEFLECT, CardId::COMPILE_DRIVER, CardId::TALK_TO_THE_HAND, CardId::BATTLE_HYMN, CardId::PROTECT,
    CardId::TRIP, CardId::INDIGNATION, CardId::DAGGER_THROW, CardId::AMPLIFY, CardId::THIRD_EYE, CardId::BRUTALITY, CardId::NIGHTMARE, CardId::WINDMILL_STRIKE, CardId::IRON_WAVE, CardId::REBOOT, CardId::RECKLESS_CHARGE, CardId::ALL_FOR_ONE,
    CardId::FOREIGN_INFLUENCE, CardId::DECAY, CardId::FAME_AND_FORTUNE, CardId::TOOLS_OF_THE_TRADE, CardId::AGGREGATE, CardId::EXPERTISE, CardId::DRAMATIC_ENTRANCE, CardId::HEMOKINESIS, CardId::BLIZZARD, CardId::CHAOS, CardId::LIVE_FOREVER, CardId::INTIMIDATE,
    CardId::ECHO_FORM, CardId::NECRONOMICURSE, CardId::JUGGERNAUT, CardId::CHOKE, CardId::CALTROPS, CardId::IMPATIENCE, CardId::DEVA_FORM, CardId::POISONED_STAB, CardId::THE_BOMB, CardId::BLUR, CardId::LIKE_WATER, CardId::BODY_SLAM,
    CardId::TRUE_GRIT, CardId::INSIGHT, CardId::SETUP, CardId::BARRAGE, CardId::CRESCENDO, CardId::SPIRIT_SHIELD, CardId::BLOOD_FOR_BLOOD, CardId::IMPERVIOUS, CardId::TRANQUILITY, CardId::EMPTY_BODY, CardId::SHRUG_IT_OFF, CardId::METEOR_STRIKE,
    CardId::ESTABLISHMENT, CardId::FASTING, CardId::CLASH, CardId::STACK, CardId::MIRACLE, CardId::CARVE_REALITY, CardId::WALLOP, CardId::THUNDERCLAP, CardId::REBOUND, CardId::FLAME_BARRIER, CardId::SEEK, CardId::ENDLESS_AGONY,
    CardId::WREATH_OF_FLAME, CardId::COLLECT, CardId::SASH_WHIP, CardId::WRAITH_FORM, CardId::MELTER, CardId::BERSERK, CardId::PUMMEL, CardId::BURNING_PACT, CardId::RIDDLE_WITH_HOLES, CardId::METALLICIZE, CardId::SELF_REPAIR, CardId::POMMEL_STRIKE,
    CardId::PAIN, CardId::RAINBOW, CardId::INNER_PEACE, CardId::BURST, CardId::ACROBATICS, CardId::RUSHDOWN, CardId::LOOP, CardId::BLIND, CardId::DOPPELGANGER, CardId::SKEWER, CardId::OMNISCIENCE, CardId::ENVENOM,
    CardId::CHILL, CardId::ADRENALINE, CardId::QUICK_SLASH, CardId::TWIN_STRIKE, CardId::BOOT_SEQUENCE, CardId::PARASITE, CardId::BASH, CardId::RITUAL_DAGGER, CardId::CLAW, CardId::WISH, CardId::CLOTHESLINE, CardId::DECEIVE_REALITY,
    CardId::MENTAL_FORTRESS, CardId::SHOCKWAVE, CardId::BECOME_ALMIGHTY, CardId::RAMPAGE, CardId::COOLHEADED, CardId::STATIC_DISCHARGE, CardId::ALPHA, CardId::HEATSINKS, CardId::VAULT, CardId::BANDAGE_UP, CardId::SCRAWL, CardId::SEVER_SOUL,
    CardId::ERUPTION, CardId::WHIRLWIND, CardId::BITE, CardId::LESSON_LEARNED, CardId::SECRET_TECHNIQUE, CardId::CALCULATED_GAMBLE, CardId::TEMPEST, CardId::COMBUST, CardId::DEEP_BREATH, CardId::DOUBT, CardId::ESCAPE_PLAN, CardId::CUT_THROUGH_FATE,
    CardId::REACH_HEAVEN, CardId::FINISHER, CardId::DARK_EMBRACE, CardId::DIE_DIE_DIE, CardId::WELL_LAID_PLANS, CardId::RAGNAROK, CardId::BUFFER, CardId::ELECTRODYNAMICS, CardId::FEAR_NO_EVIL, CardId::SEEING_RED, CardId::SANDS_OF_TIME, CardId::SMITE,
    CardId::VIOLENCE, CardId::DISARM, CardId::TURBO, CardId::PANACHE, CardId::EQUILIBRIUM, CardId::FIEND_FIRE, CardId::TERROR, CardId::FORCE_FIELD, CardId::DAZED, CardId::BARRICADE, CardId::ARMAMENTS, CardId::HAVOC,
    CardId::SECRET_WEAPON, CardId::APOTHEOSIS, CardId::SWEEPING_BEAM, CardId::FEEL_NO_PAIN, CardId::FTL, CardId::RIP_AND_TEAR, CardId::DARKNESS, CardId::CORRUPTION, CardId::HEEL_HOOK, CardId::BLASPHEMY, CardId::INJURY, CardId::DOUBLE_ENERGY,
    CardId::RAGE, CardId::HEADBUTT, CardId::MACHINE_LEARNING, CardId::REINFORCED_BODY, CardId::DEFEND_PURPLE, CardId::LIMIT_BREAK, CardId::ENTRENCH, CardId::NOXIOUS_FUMES, CardId::INFINITE_BLADES, CardId::PHANTASMAL_KILLER, CardId::WAVE_OF_THE_HAND, CardId::MALAISE,
    CardId::CHARGE_BATTERY, CardId::DEFEND_RED, CardId::MAYHEM, CardId::REFLEX, CardId::STUDY, CardId::EXPUNGER, CardId::SENTINEL, CardId::SURVIVOR, CardId::WILD_STRIKE, CardId::DEFEND_GREEN, CardId::HAND_OF_GREED, CardId::MEDITATE,
    CardId::EVISCERATE, CardId::FLASH_OF_STEEL, CardId::DEFEND_BLUE, CardId::BATTLE_TRANCE, CardId::FORETHOUGHT, CardId::DUALCAST, CardId::AUTO_SHIELDS, CardId::PERSEVERANCE, CardId::SWIVEL, CardId::HEAVY_BLADE, CardId::SLIMED, CardId::CLUMSY,
    CardId::BIASED_COGNITION, CardId::SEARING_BLOW, CardId::DEVOTION, CardId::REPROGRAM, CardId::HOLOGRAM, CardId::CORPSE_EXPLOSION, CardId::SECOND_WIND, CardId::ENLIGHTENMENT, CardId::PURITY, CardId::PANACEA, CardId::BULLSEYE, CardId::DASH,
    CardId::WORSHIP, CardId::CONCLUDE, CardId::THROUGH_VIOLENCE, CardId::TRANSMUTATION, CardId::APPARITION, CardId::BACKSTAB, CardId::CHRYSALIS, CardId::FOLLOW_UP, CardId::VOID, CardId::SCRAPE, CardId::FEED, CardId::VIGILANCE,
    CardId::RUPTURE, CardId::ALCHEMIZE, CardId::DISCOVERY, CardId::BEAM_CELL, CardId::LEAP, CardId::CURSE_OF_THE_BELL, CardId::BOUNCING_FLASK, CardId::PRESSURE_POINTS, CardId::BLUDGEON, CardId::FINESSE, CardId::SLICE, CardId::RECYCLE,
    CardId::BACKFLIP, CardId::OUTMANEUVER, CardId::BLOODLETTING, CardId::BRILLIANCE, CardId::MAGNETISM, CardId::CONCENTRATE, CardId::SKIM, CardId::WHITE_NOISE, CardId::CAPACITOR, CardId::COLD_SNAP, CardId::CRUSH_JOINTS, CardId::MASTER_OF_STRATEGY,
    CardId::FLECHETTES, CardId::TANTRUM, CardId::PERFECTED_STRIKE, CardId::STRIKE_BLUE, CardId::THUNDER_STRIKE, CardId::CARNAGE, CardId::MASTERFUL_STAB, CardId::NIRVANA, CardId::EVALUATE, CardId::PREPARED, CardId::GOOD_INSTINCTS, CardId::DROPKICK,
    CardId::SWIFT_STRIKE, CardId::NORMALITY, CardId::STRIKE_GREEN, CardId::MASTER_REALITY, CardId::OMEGA, CardId::HYPERBEAM, CardId::ACCURACY, CardId::SWORD_BOOMERANG, CardId::EMPTY_MIND, CardId::PRIDE, CardId::DEFRAGMENT, CardId::JACK_OF_ALL_TRADES,
    CardId::DEMON_FORM, CardId::FIRE_BREATHING, CardId::GHOSTLY_ARMOR, CardId::WEAVE, CardId::SAFETY, CardId::METAMORPHOSIS, CardId::PROSTRATE, CardId::SIGNATURE_MOVE, CardId::UPPERCUT, CardId::PIERCING_WAIL, CardId::MIND_BLAST, CardId::NEUTRALIZE,
    CardId::MULTI_CAST, CardId::SHAME, CardId::DOOM_AND_GLOOM, CardId::EVOLVE, CardId::DOUBLE_TAP, CardId::SUCKER_PUNCH, CardId::BURN, CardId::CONJURE_BLADE, CardId::STRIKE_RED, CardId::JUDGMENT, CardId::FOOTWORK, CardId::STRIKE_PURPLE,
    CardId::STEAM_BARRIER, CardId::DISTRACTION, CardId::DODGE_AND_ROLL, CardId::THINKING_AHEAD, CardId::EMPTY_FIST, CardId::ALL_OUT_ATTACK, CardId::FLYING_KNEE, CardId::PREDATOR, CardId::PRAY, CardId::MADNESS
};
}
}

#endif
